
version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: dev-admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: health_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      DATABASE_URL: postgresql+psycopg2://dev-admin:password123@db:5432/health_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
        